---
name: Checks

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run Unit Tests
        run: python manage.py test

      - name: Install Dependecies
        run: pip install flake8

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "F401"
          exclude: ".git,__pycache__,migrations,settings.py,manage.py"
          max-line-length: "100"

