---
name: Checks

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Flake8
        run: |
          source ../env/bin/activate
          flake8