---
name: Checks

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependecies
        run: pip install flake8

      - name: Run Linting tool
        run: flake8

